version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mds-app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SWAGGER_SERVER_URL=${SWAGGER_SERVER_URL:-http://localhost:8080}
      - DATABASE_URL=${DATABASE_URL}
      - API_TOKEN=${API_TOKEN}
      - FINALIZATION_WINDOW_HOURS=${FINALIZATION_WINDOW_HOURS:-24}
      - SUPPORTED_TIMEFRAMES=${SUPPORTED_TIMEFRAMES:-1m,5m,15m,30m,1h,4h,1d}
    ports:
      - "8080:8080"
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: mds-timescaledb-prod
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-m-data-storage}
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-m-data-storage}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_prod:
    driver: local


