# Binance Broker Configuration
broker_id: "binance"
name: "Binance"
type: "crypto"
enabled: true

# Connection Settings
connection:
  base_url: "https://api.binance.com"
  websocket_url: "wss://stream.binance.com:9443/ws"
  timeout: "30s"
  rate_limit:
    requests_per_minute: 1200
    weight_per_minute: 6000

# Authentication (optional for public data)
auth:
  api_key: ""
  secret_key: ""
  passphrase: ""

# Supported Markets
markets:
  - "spot"
  - "futures"

# Supported Data Types
data_types:
  - "ticker"
  - "candle"
  - "orderbook"

# Subscription Settings
subscriptions:
  # Maximum number of symbols in one WebSocket connection
  max_symbols_per_connection: 200

  # Automatic reconnection
  auto_reconnect: true
  reconnect_delay: "5s"
  max_reconnects: 10

  # Ping/pong for connection maintenance
  ping_interval: "30s"
  pong_timeout: "10s"

# Symbol Mapping (if needed)
symbol_mapping:
  # Internal symbol: Broker symbol
  "BTC/USDT": "BTCUSDT"
  "ETH/USDT": "ETHUSDT"

# Settings for different data types
ticker_config:
  # Ticker update interval (if supported)
  update_interval: "1s"

candle_config:
  # Supported timeframes
  supported_timeframes:
    - "1s"
    - "1m"
    - "3m"
    - "5m"
    - "15m"
    - "30m"
    - "1h"
    - "2h"
    - "4h"
    - "6h"
    - "8h"
    - "12h"
    - "1d"
    - "3d"
    - "1w"
    - "1M"

orderbook_config:
  # Orderbook depth
  depth: 20
  # Update interval
  update_interval: "100ms"

# Futures settings
futures_config:
  # Additional data for futures
  funding_rate: true
  mark_price: true
  open_interest: true

# Error handling
error_handling:
  # Maximum number of consecutive errors before disconnection
  max_consecutive_errors: 5
  # Delay after error
  error_delay: "1s"
  # Log all errors
  log_all_errors: true

# Monitoring
monitoring:
  # Connection health check
  health_check_interval: "30s"
  # Таймаут для проверки здоровья
  health_check_timeout: "10s"
  # Метрики производительности
  collect_metrics: true
