# Конфигурация приложения M-Data-Storage
app:
  name: "m-data-storage"
  version: "1.0.0"
  environment: "development"
  debug: true
  timeout: "30s"

# Конфигурация API сервера
api:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "10s"
  shutdown_timeout: "30s"
  
  # CORS настройки
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "X-API-Key"]
  
  # Аутентификация
  auth:
    enabled: false
    jwt_secret: ""
    jwt_expiry: "24h"
    api_key_header: "X-API-Key"

# Конфигурация баз данных
database:
  # SQLite для метаданных
  sqlite:
    path: "./data/metadata.db"
    max_open_conns: 10
    max_idle_conns: 5
    conn_max_lifetime: "1h"
    wal_mode: true
    foreign_keys: true
  
  # QuestDB для временных рядов
  questdb:
    host: "localhost"
    port: 8812
    database: "qdb"
    username: ""
    password: ""
    max_open_conns: 20
    max_idle_conns: 10
    conn_max_lifetime: "1h"
    query_timeout: "30s"

# Конфигурация логирования
logging:
  level: "debug"
  format: "json"
  output: "stdout"
  file: ""
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Конфигурация хранилища
storage:
  retention_period: "720h"  # 30 дней
  vacuum_interval: "24h"
  max_storage_size: 10737418240  # 10GB
  batch_size: 1000
  flush_interval: "5s"

# Конфигурация брокеров
brokers:
  config_path: "./configs/brokers"
  reconnect_delay: "5s"
  max_reconnects: 10
  health_check_interval: "30s"
